server:
  port: 8695
  servlet:
    context-path: /
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: utf-8
      force: true
  datasource:
    name: warehouse
    url: jdbc:mysql://localhost:3306/warehouse
    username: root
    password: 19970923
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/zzu/zjh/mapper/*.xml
  type-aliases-package: com.zzu.zjh.entity